#!/bin/bash

# Kill off other instances, if any
killall -qw echoserver >/dev/null 2>&1
sleep 1

./echoserver -t >/dev/null 2>&1 &
sleep 1
pid=$(cat echoserver.pid) || exit 1

X=$(echo "hello" | nc localhost 3000)
if test "x$X" != "xhello"; then
    exit 1
fi

kill -TERM $pid
sleep 1

# Now do the same with SSL
./echoserver >/dev/null 2>&1 &
sleep 1
pid=$(cat echoserver.pid) || exit 1

X=$(echo "hellossl" | nc --ssl localhost 3000)
if test "x$X" != "xhellossl"; then
    exit 1
fi

kill -TERM $pid
exit 0
