.TH array_nelem 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm array_nelem
.Nd Returns the number of elements in a dynamic array
.SH SYNOPSIS
.B #include <meta_array.h>
.Fo "int array_nelem"
.Fa "array p"
.Fc
.SH DESCRIPTION
Returns the number of elements in a dynamic array
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
