.TH array_get 3
.SH NAME
.Nm array_get
.Nd Get an element from the array
.SH SYNOPSIS
.Fd #include <meta_array.h>
.Fo "int array_get"
.Fa "array p "
.Fa "size_t idx"
.Fc
.SH DESCRIPTION
Returns one element or NULL if the index is out of bounds.
The index is zero-based.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
