.TH array_extend 3 2016-01-30 "" "The Meta C Library"
.SH NAME
array_extend \- Extend a dynamic array
.SH SYNOPSIS
.B #include <meta_array.h>
.sp
.BI "int array_extend(array p, size_t nelem);

.SH DESCRIPTION
Adds room for nelem new elements in the array.
Returns 0 if the function was unable to extend the array, else 1.
