.TH array_nelem 3 2016-01-30 "" "The Meta C Library"
.SH NAME
array_nelem \- Returns the number of elements in a dynamic array
.SH SYNOPSIS
.B #include <meta_array.h>
.sp
.BI "int array_nelem(array p);

.SH DESCRIPTION
Returns the number of elements in a dynamic array
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
