.TH array_get 3 2016-01-30 "" "The Meta C Library"
.SH NAME
array_get \- Get an element from the array
.SH SYNOPSIS
.B #include <meta_array.h>
.sp
.BI "int array_get(array p, size_t idx);

.SH DESCRIPTION
Returns one element or NULL if the index is out of bounds.
The index is zero-based.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
