.TH bitset_unmap 3 2016-01-30 "" "The Meta C Library"
.SH NAME
bitset_unmap \- Unmaps mapped memory.
.SH SYNOPSIS
.B #include <meta_bitset.h>
.sp
.Fo "void bitset_unmap"
.Fa "bitset b"
.Fc
.SH DESCRIPTION
Frees memory allocated by bitset, but the memory used to store 
bits is untouched. Memory mapped bitsets must be unmapped using 
this function. Do not use 
.Nm bitset_free()
if the bitset was 
created using 
.Nm bitset_map()
or
.Nm bitset_remap().
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
