.TH bitset_data 3 2016-01-30 "" "The Meta C Library"
.SH NAME
bitset_data \- Return a pointer to the internal data structure.
.SH SYNOPSIS
.B #include <meta_bitset.h>
.sp
.BI "void* bitset_data(bitset b);

.SH DESCRIPTION
Returns a void pointer to the data that implements the bitset.
.PP
You might ask why this function is needed? The reason is that 
we then can 'move' the bitset from memory to e.g. a memory mapped file.
We can write the bitsets to files using this function and
bitset_size() as arguments to write().
