.TH bitset_set_all 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm bitset_set_all
.Nd Set all bits in a bitset to 1.
.SH SYNOPSIS
.B #include <meta_bitset.h>
.Fo "void bitset_set_all"
.Fa "bitset b"
.Fc
.SH DESCRIPTION
.Nm
sets all bits in a bitset to 1.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
