.TH bitset_and_eq 3
.SH NAME
.Nm bitset_and_eq
.Nm bitset_or_eq
.Nm bitset_xor_eq
.Nd Binary AND/OR/XOR two bitsets.
.SH SYNOPSIS
.Fd #include <meta_bitset.h>
.Fo "void bitset_and_eq"
.Fa "bitset a"
.Fa "bitset b"
.Fc
.Fo "void bitset_or_eq"
.Fa "bitset a"
.Fa "bitset b"
.Fc
.Fo "void bitset_xor_eq"
.Fa "bitset a"
.Fa "bitset b"
.Fc
.SH DESCRIPTION
Binary AND two bitsets, and store the result in the first set.
These three functions perform the equivalent of a OP = b;
where OP is &, | or ^.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
