.TH bitset_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm bitset_new
.Nm bitset_free
.Nd Allocate and free bitsets.
.SH SYNOPSIS
.B #include <meta_bitset.h>
.sp
.BI "bitset bitset_new(size_t bitcount);

.BI "void bitset_free(bitset b);

.SH DESCRIPTION
.Nm bitset_new()
creates a new bitset with room for bitcount bits.
.PP
.Nm bitset_free()
frees a bitset previously created by 
.Nm bitset_new().
