.TH bitset_size 3
.SH NAME
.Nm bitset_size
.Nd Returns size of bitset in bytes
.SH SYNOPSIS
.Fd #include <meta_bitset.h>
.Fo "size_t bitset_size"
.Fa "bitset b"
.Fc
.SH DESCRIPTION
Returns the number of bytes used by the bitset to
store bits. Use it if you e.g. want to write the
bitset to a file using standar C I/O functions.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
