.TH bitset_is_set 3 2016-01-30 "" "The Meta C Library"
.SH NAME
bitset_is_set \- Is a bit set
.SH SYNOPSIS
.B #include <meta_bitset.h>
.Fo "int bitset_is_set"
.Fa "bitset b"
.Fa "size_t i"
.Fc
.SH DESCRIPTION
Returns 1 if the bit specified is set, 0 if not.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
