.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th meta_bitset 3
.Sh NAME
.Nm meta_bitset
.Nd Dynamic bitset ADT
.Sh SYNOPSIS
.Fd #include <meta_bitset.h>
.Fo "bitset bitset_new"
.Fa "size_t bitcount"
.Fc
.Fo "void bitset_free"
.Fa "bitset b"
.Fc
.Sh DESCRIPTION
.Nm bitset_new()
creates a new bitset with room for bitcount bits.
.Pp
.Nm bitset_free()
frees a bitset previously created by 
.Nm bitset_new().
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
