.TH bitset_and 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm bitset_and
.Nm bitset_or
.Nm bitset_xor
.Nd Binary AND/OR/XOR two bitsets. Return the result in a new bitset.
.SH SYNOPSIS
.B #include <meta_bitset.h>
.sp
.BI "bitset bitset_and(bitset b, bitset c);

.BI "bitset bitset_or(bitset b, bitset c);

.BI "bitset bitset_xor(bitset b, bitset c);

.SH DESCRIPTION
Binary AND two bitsets. Return the result in a new bitset.
These three functions perform the equivalent of a = b OP c;
where OP is &, | or ^.
.PP
Remember to free the returned bitset.
.SH ERRORS
The functions will return if they were unable to allocate room for
the new bitset.
