.TH cache_add 3
.SH NAME
.Nm cache_add
.Nd Add an element to a cache
.SH SYNOPSIS
.Fd #include <meta_cache.h>
.Fo "int cache_add"
.Fa "cache c"
.Fa "size_t id"
.Fa "void *data"
.Fa "size_t cb"
.Fa "int pin"
.Fc
.SH DESCRIPTION
Add a new item to the cache. The item is identified
by the id parameter and has size cb. The data pointer
must be a pointer to allocated memory as it will be
freed using the free() function whenever the cache 
needs to discard it. Pinned items will not be discarded
during normal operation, but the memory will be freed
when the cache is deleted.
.Pp
.Nm
returns 1 if the item was added successfully.
The function will return 0 if an item with the same id
already exists. 
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
