.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th cache_exists 3
.Sh NAME
.Nm cache_exists
.Nd Checks if an item exists or not
.Sh SYNOPSIS
.Fd #include <meta_cache.h>
.Fo "int cache_exists"
.Fa "cache c"
.Fa "size_t id"
.Fc
.Sh DESCRIPTION
Checks if an item exists or not
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
