.TH cache_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cache_new
.Nm cache_free
.Nd Create and destroy a cache.
.SH SYNOPSIS
.B #include <meta_cache.h>
.sp
.Fo "cache cache_new"
.Fa "size_t nelem"
.Fa "size_t hotlist_nelem"
.Fa "size_t cb"
.Fc
.Fo "void cache_free"
.Fa "cache c"
.Fa "dtor cleanup"
.Fc
.SH DESCRIPTION
.Nm cache_new()
creates a new cache. The cache will have room for nelem elements,
and we keep hotlist_nelem elements on a hotlist, which stores the most
active items.
.PP
The total size of the cache cannot exceed cb bytes in size.
.PP
.Nm cache_free()
destroys a cache. 
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
