.TH cache_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cache_new
.Nm cache_free
.Nd Create and destroy a cache.
.SH SYNOPSIS
.B #include <meta_cache.h>
.sp
.BI "cache cache_new(size_t nelem, size_t hotlist_nelem, size_t cb);

.BI "void cache_free(cache c, dtor cleanup);

.SH DESCRIPTION
.Nm cache_new()
creates a new cache. The cache will have room for nelem elements,
and we keep hotlist_nelem elements on a hotlist, which stores the most
active items.
.PP
The total size of the cache cannot exceed cb bytes in size.
.PP
.Nm cache_free()
destroys a cache. 
