.TH cache_remove 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cache_remove \- Remove an item from a cache
.SH SYNOPSIS
.B #include <meta_cache.h>
.sp
.Fo "int cache_remove"
.Fa "cache c"
.Fa "size_t id"
.Fc
.SH DESCRIPTION
Remove an item from a cache
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
