.TH cache_exists 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cache_exists
.Nd Checks if an item exists or not
.SH SYNOPSIS
.B #include <meta_cache.h>
.Fo "int cache_exists"
.Fa "cache c"
.Fa "size_t id"
.Fc
.SH DESCRIPTION
Checks if an item exists or not
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
