.TH cache_get 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cache_get \- Retrieves an item from the cache.
.SH SYNOPSIS
.B #include <meta_cache.h>
.sp
.Fo "int cache_get"
.Fa "cache c"
.Fa "size_t id"
.Fa "void **pdata"
.Fa "size_t *pcb"
.Fc
.SH DESCRIPTION
Retrieves an item from the cache.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
