.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th cache_new 3
.Sh NAME
.Nm cache_new
.Nm cache_free
.Nd Create and destroy a cache.
.Sh SYNOPSIS
.Fd #include <meta_cache.h>
.Fo "cache cache_new"
.Fa "size_t nelem"
.Fa "size_t hotlist_nelem"
.Fa "size_t cb"
.Fc
.Fo "void cache_free"
.Fa "cache c"
.Fa "dtor cleanup"
.Fc
.Sh DESCRIPTION
.Nm cache_new()
creates a new cache. The cache will have room for nelem elements,
and we keep hotlist_nelem elements on a hotlist, which stores the most
active items.
.Pp
The total size of the cache cannot exceed cb bytes in size.
.Pp
.Nm cache_free()
destroys a cache. 
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
