.TH cache_get 3
.SH NAME
.Nm cache_get
.Nd Retrieves an item from the cache.
.SH SYNOPSIS
.Fd #include <meta_cache.h>
.Fo "int cache_get"
.Fa "cache c"
.Fa "size_t id"
.Fa "void **pdata"
.Fa "size_t *pcb"
.Fc
.SH DESCRIPTION
Retrieves an item from the cache.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
