.TH meta_configfile 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm meta_configfile
.Nd Generic configuration file ADT
.SH SYNOPSIS
.B #include <meta_configfile.h>
.Fo "int configfile_exists"
.Fa "configfile cf"
.Fa "const char *name"
.Fc
.SH DESCRIPTION
.Nm
returns 1 if a variable with that name exists in the configuration file,
and 0 if not.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

