.TH configfile_free 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_free \- Frees all memory used by the configfile ADT.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.Fo "void configfile_free"
.Fa "configfile cf"
.Fc
.SH DESCRIPTION
Frees all memory used by the configfile ADT.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

