.TH configfile_get_int 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_get_int \- Retrieve an int value from the configfile.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.BI "int configfile_get_int(configfile cf, const char *name, int *value);

.SH DESCRIPTION
Retrieve an int value from the configfile.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

