.TH configfile_get_ulong 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_get_ulong \- Retrieve an unsigned long value from the configfile.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.BI "int configfile_get_ulong(configfile cf, const char *name, unsigned long *value);

.SH DESCRIPTION
Retrieve an unsigned long value from the configfile.

