.TH meta_configfile 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_configfile \- Generic configuration file ADT
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.BI "int configfile_exists(configfile cf, const char *name);

.SH DESCRIPTION
.Nm
returns 1 if a variable with that name exists in the configuration file,
and 0 if not.

