.TH configfile_get_uint 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm configfile_get_uint
.Nd Retrieve an unsigned int value from the configfile.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.Fo "int configfile_get_uint"
.Fa "configfile cf"
.Fa "const char *name"
.Fa "unsigned int *value"
.Fc
.SH DESCRIPTION
Retrieve an unsigned int value from the configfile.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

