.TH configfile_read 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_read \- Read and parse a configuration file
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.Fo "configfile configfile_read"
.Fa "const char *path"
.Fc
.SH DESCRIPTION
Read and parse a configuration file.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

