.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th configfile_free 3
.Sh NAME
.Nm configfile_free
.Nd Frees all memory used by the configfile ADT.
.Sh SYNOPSIS
.Fd #include <meta_configfile.h>
.Fo "void configfile_free"
.Fa "configfile cf"
.Fc
.Sh DESCRIPTION
Frees all memory used by the configfile ADT.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

