.TH configfile_get_uint 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_get_uint \- Retrieve an unsigned int value from the configfile.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.BI "int configfile_get_uint(configfile cf, const char *name, unsigned int *value);

.SH DESCRIPTION
Retrieve an unsigned int value from the configfile.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

