.TH configfile_get_long 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_get_long \- Retrieve an long value from the configfile.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.BI "int configfile_get_long(configfile cf, const char *name, long *value);

.SH DESCRIPTION
Retrieve an long value from the configfile.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

