.TH configfile_get_string 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_get_string \- Retrieve a string from the configfile ADT
.SH SYNOPSIS
.B #include <meta_configfile.h>
.sp
.Fo "int configfile_get_string"
.Fa "configfile cf"
.Fa "const char *name"
.Fa "char *value"
.Fa "size_t cb"
.Fc
.SH DESCRIPTION
Retrieve a string from the configfile ADT
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

