.TH configfile_read 3
.SH NAME
.Nm configfile_read
.Nd Read and parse a configuration file
.SH SYNOPSIS
.Fd #include <meta_configfile.h>
.Fo "configfile configfile_read"
.Fa "const char *path"
.Fc
.SH DESCRIPTION
Read and parse a configuration file.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

