.TH configfile_free 3
.SH NAME
.Nm configfile_free
.Nd Frees all memory used by the configfile ADT.
.SH SYNOPSIS
.Fd #include <meta_configfile.h>
.Fo "void configfile_free"
.Fa "configfile cf"
.Fc
.SH DESCRIPTION
Frees all memory used by the configfile ADT.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

