.TH configfile_get_ulong 3 2016-01-30 "" "The Meta C Library"
.SH NAME
configfile_get_ulong \- Retrieve an unsigned long value from the configfile.
.SH SYNOPSIS
.B #include <meta_configfile.h>
.Fo "int configfile_get_ulong"
.Fa "configfile cf"
.Fa "const char *name"
.Fa "unsigned long *value"
.Fc
.SH DESCRIPTION
Retrieve an unsigned long value from the configfile.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

