.TH connection_close 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_close() \- Closes a connection
.SH SYNOPSIS
.B #include <connection.h>
.sp
.BI "int connection_close(connection conn);

.SH DESCRIPTION
.Nm
closes the connection to the client. 
.Nm
will try to write any pending data to the socket and then 
close the connection.  It will always close the socket,
but may report errors when flushing write-buffer.
.PP
Users of tcp_server never has to call this function.
.SH RETURN VALUE
.Nm
returns returns 1 on success, else 0. 
