.TH connection_flush 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_flush() \- Flush the write buffer
.SH SYNOPSIS
.B #include <connection.h>
.sp
.BI "int connection_flush(connection conn);

.SH DESCRIPTION
.Nm
writes data in the write buffer to the socket.
.SH RETURN VALUE
.Nm
returns 1 if the buffer was written to the socket, 0 if an error occured.
.SH SEE ALSO
.Xr connection_putc 3 ,
.Xr connection_write 3 ,
.Xr sock_write 3
.SH EXAMPLE
Here we flush once for every character to make the echo server
as interactive as possible. This is not recommended as it will create
more load on the server and more context switches.
.in +4n
.nf
.B #include <tcp_server.h>
.sp
.B #include <connection.h>
.sp
void* echoserverfn(void* arg)
{
    int c;
    connection conn = arg;
    tcp_server s = connection_arg2(conn);
    while(!tcp_server_shutting_down(s) 
    && connection_getc(conn, &c)) {
        connection_putc(conn, c);
        connection_flush(conn);
    }
    return NULL;
}
.nf
.in
