.TH connection_getc 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm connection_getc()
.Nm connection_putc()
.Nd read or write one character 
.SH SYNOPSIS
.B #include <connection.h>
.Fo "int connection_getc"
.Fa "connection conn"
.Fa "int* pch"
.Fc
.Fo "int connection_putc"
.Fa "connection conn"
.Fa "int ch"
.Fc
.SH DESCRIPTION
.Nm connection_getc()
reads one character from the socket or the read buffer.
.PP
.Nm connection_putc()
writes one character to the socket or write buffer.
.SH RETURN VALUE
Both functions return 1 on success and 0 if an error occured.
.SH SEE ALSO
.Xr connection_read 3 ,
.Xr connection_gets 3 ,
.Xr connection_puts 3 ,
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
