.TH connection_putc 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm connection_putc()
.Nd Write one character
.SH SYNOPSIS
.B #include <connection.h>
.SH DESCRIPTION
.Nm
writes one character to the connection.
return 1 if the character was written, or 0 if an error occured. 
.SH SEE ALSO
.Xr connection_flush
.SH EXAMPLE
.Bd -literal
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
