.TH connection_get_fd 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_get_fd() \- Return file descriptor
.SH SYNOPSIS
.B #include <connection.h>
.Fo "int connection_get_fd"
.Fa "connection conn"
.Fc
.SH DESCRIPTION
.Nm
Returns the file descriptor or -1 if no valid file descriptor
has been assigned to the connection.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
