.TH connection_set_fd 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm connection_set_fd()
.Nd Assign a file descriptor to the connection object.
.SH SYNOPSIS
.B #include <connection.h>
.Fo "void connection_set_fd"
.Fa "connection conn"
.Fa "int fd"
.Fc
.SH DESCRIPTION
.Nm
assigns a new file descriptor to the connection ADT. The fd
will normally represent an open socket.
.PP
Users of the tcp_server ADT never has to call this function, in fact
they never should.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
