.TH connection_set_params 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_set_params() \- Set parameters for the current connection
.SH SYNOPSIS
.B #include <connection.h>
.sp
.BI "void connection_set_params(connection conn, int fd, struct sockaddr_in* paddr);

.SH DESCRIPTION
.Nm
assigns a file descriptor and a pointer to a sockaddr_in to 
the connection.
.PP
Users of the tcp_server ADT never has to call this function, in fact
they never should.
