.TH connection_ungetc 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_ungetc() \- connection_ungetc
.SH SYNOPSIS
.B #include <connection.h>
.sp
.Fo "int connection_ungetc"
.Fa "connection conn"
.Fa "int c"
.Fc
.SH DESCRIPTION
.Nm
pushes
.Fa c
back to
.Fa conn
, where it is available for subsequent read operations. 
Pushed-back characters will be returned in reverse order; only
one pushback is guaranteed.
.PP
The current version ignores
.Fa c
and just adjusts the read buffers internal index. For that reason
you have to unget the same character(s) that you read from 
.Fa conn.
.SH RETURN VALUE
.Nm
return 1 on success, 0 if an error occured.  The typical error
would be that the read buffer is full, but that cannot happen
if the call to connection_ungetc() was preceeded
by a call to connection_getc().
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
