.TH connection_readbuf_size 3
.SH NAME
.Nm connection_readbuf_size()
.Nd Returns size of read buffer
.SH SYNOPSIS
.Fd #include <connection.h>
.Fo "size_t connection_readbuf_size"
.Fa "connection conn"
.Fc
.SH DESCRIPTION
.Nm
returns the size of the readbuffer.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
