.TH connection_set_persistent 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm connection_set_persistent()
.Nm connection_is_persistent()
.Nd Set or get the connection flag
.SH SYNOPSIS
.B #include <connection.h>
.Fo "void connection_set_persistent"
.Fa "connection conn"
.Fa "int val"
.Fc
.Fo "int connection_is_persistent"
.Fa "connection conn"
.Fc
.SH DESCRIPTION
.Nm connection_set_persistent()
sets the persistent flag of the connection to either true
or false. This flag is not used by the connection object itself,
but is an attribute for the connection which can be used by
protocol handlers (read:http 1.1).
.PP
.Nm connection_is_persistent()
returns if the connection is persistent or not. 
.PP
Users of the tcp_server ADT never has to call these function.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
