.TH connection_writebuf_size 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_writebuf_size \- connection_writebuf_size
.SH SYNOPSIS
.B #include <connection.h>
.Fo
.Fc
.SH DESCRIPTION
Returns the size of the write buffer.
size_t connection_writebuf_size(connection conn);
.SH EXAMPLE
.Bd -literal
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
