.TH connection_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_new \- Create a new connection
.SH SYNOPSIS
.B #include <connection.h>
.sp
.BI "connection connection_new(int timeout_reads, int timeout_writes, int retries_reads, int retries_writes, void* arg2);

.SH DESCRIPTION
.Nm
creates an instance of the connection ADT. 
.PP
The tcp_server creates a given number of connections when the 
tcp_server is initialized. These connections are later supplied
to the caller of the tcp_server whenever a new connection from
a client is accepted by the server.
.PP
The arg2 parameter is an optional pointer value which will be 
returned to the callback function when a new connection is made.
One possible and quite common use of arg2 is to store a handle
to the service that the tcp_server is used for. Imagine that
you have created more than one http_server within the same process.
Each http_server will then have its own instance, possibly 
represented as a malloced() pointer. At the same time, both
http_servers can share the callback function. arg2 can be used
to identify which http_server the connection was made to.
.PP
Users of tcp_server never has to call this function.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
