.TH connection_arg2 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_arg2() \- Returns a pointer to argument 2.
.SH SYNOPSIS
.B #include <connection.h>
.sp
.BI "void* connection_arg2(connection conn);

.SH DESCRIPTION
Returns the value of arg2 that was supplied when the connection was 
created. The object pointed to varies with the type of server you
are using.
.SH EXAMPLE
.Bd -literal
.Ed
.SH SEE ALSO
.Xr connection_new 3
