.TH connection_read 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_read() \- connection_read
.SH SYNOPSIS
.B #include <connection.h>
.sp
.Fo "ssize_t connection_read"
.Fa "connection conn"
.Fa "void *buf"
.Fa "size_t count"
.Fc
.SH DESCRIPTION
.Nm
attempts to read 
.Fa cb
bytes from the connection. 
.PP
.Nm
will read up to 
.Fa cb
bytes and return the number of bytes read.
.SH SEE ALSO
.Xr connection_set_read_buffer 3 ,
.Xr connection_write 3
.SH EXAMPLE
Here we read 10 and 10 bytes from the socket. If the input
arrives too slowly, 
.Nm
returns 0 and sets errno to EAGAIN. We therefore test for this.
.PP
.Bd -literal
.B #include <tcp_server.h>
.sp
.B #include <connection.h>
.sp
.B #include <errno.h>
.sp

void* echoserverfn(void* arg)
{
	connection conn = arg;
	char line[1024];
	ssize_t nread;

	errno = 0;
	while ((nread = connection_read(conn, line, 10)) >= 0) {
		connection_write(conn, line, nread);
		connection_flush(conn);
	}

	return NULL;
}
int main(void)
{
	tcp_server s = tcp_server_new();
	tcp_server_set_service_function(s, echoserverfn, s);
	tcp_server_init(s);
	tcp_server_get_root_resources(s);
	tcp_server_start(s);
	
	tcp_server_free(s);
	return 0;
}
	
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
