.TH connection 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm connection
.Nd connection
.SH SYNOPSIS
.B #include <connection.h>
.SH DESCRIPTION
An ADT for buffered reads and writes from a file descriptor.
The connection class is used, in conjunction with meta_socket.h,
meta_membuf.h and tcp_server.h, to serve TCP/IP connections.
A connection has a read buffer and a write buffer.
 Declaration of our connection ADT
typedef struct connection_tag* connection;
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
