.TH connection_discard 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_discard() \- Discard a connection
.SH SYNOPSIS
.B #include <connection.h>
.Fo "void connection_discard"
.Fa "connection conn"
.Fc
.SH DESCRIPTION
.Nm
discards a connection by closing it. Errors are ignored.
Data in the write buffer will not be written. 
.PP
Users of tcp_server never has to call this function.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
