.TH connection_free 3 2016-01-30 "" "The Meta C Library"
.SH NAME
connection_free \- Free a connection object
.SH SYNOPSIS
.B #include <connection.h>
.sp
.BI "void connection_free(connection conn);

.SH DESCRIPTION
.Nm
frees the connection object. All data in the buffers will be
discarded, so call the appropriate function before freeing the 
connection object. 
.PP
Note that the read and write buffers will not be freed, you must
free them yourself. 
.PP
Users of the tcp_server ADT never has to call this function.
.SH SEE ALSO
.Xr connection_discard
.Xr connection_close
