.TH create_client_socket 3 2016-01-30 "" "The Meta C Library"
.SH NAME
create_client_socket \- Y
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.BI "meta_socket create_client_socket(const char *host, int port);

.SH DESCRIPTION
.Nm
Connects to a host on a port.
This function calls gethostbyname() to get host info, and
it connects to the h_addr member of struct hostent. h_addr
is an alias for h_addrlist[0].
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
