.TH create_server_socket 3 2016-01-30 "" "The Meta C Library"
.SH NAME
create_server_socket \- Y
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.BI "meta_socket create_server_socket(int unix_socket, const char *host, int port);

.SH DESCRIPTION
.Nm
Creates a server socket.
This function calls socket(), sets some socket options,
binds the socket to a host/port and calls listen with a
backlog of 100.
.PP 
If unix_socket is 1, then the function will create a Unix socket,
else it will create a regular AF_INET socket.
.PP
A server socket is ready to accept connections.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
