.TH cstring_concat 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cstring_concat()
.Nm cstring_concat2()
.Nm cstring_concat3()
.Nd Concatenates strings
.SH SYNOPSIS
.B #include <cstring.h>
.Fo "int cstring_concat"
.Fa "cstring dest"
.Fa "const char* src"
.Fc
.Fo "int cstring_concat2"
.Fa "cstring dest"
.Fa "const char* src1"
.Fa "const char* src2"
.Fc
.Fo "int cstring_concat3"
.Fa "cstring dest"
.Fa "const char* src1"
.Fa "const char* src2"
.Fa "const char* src3"
.Fc
.SH DESCRIPTION
.Nm cstring_concat()
appends the
.Fa src
string to 
.Fa dest.
.Nm cstring_concat2()
appends two strings to 
.Fa dest,
and 
.Nm cstring_concat3()
appends 3 strings to 
.Fa dest.
.SH EXAMPLE
.Bd -literal
const char *myvar = "some value";
cstring s;
	
if( (s = cstring_new()) != NULL)
	cstring_concat3(s, "<h1>", myvar, "</h1>");
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
