.TH cstring_reverse 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_reverse() \- Reverse the contents of a cstring.
.SH SYNOPSIS
.B #include <cstring.h>
.Fo "void cstring_reverse"
.Fa "cstring s"
.Fc
.SH DESCRIPTION
.Nm
reverses the contents of 
.Fa s.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
