.TH cstring_printf 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cstring_printf()
.Nm cstring_vprintf()
.Nd formatted data conversion
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.BI "int cstring_printf(cstring dest, size_t needs_max, const char* fmt, ...);

.BI "int cstring_vprintf(cstring dest, size_t needs_max, const char* fmt, va_list ap);

.SH DESCRIPTION
.Nm cstring_printf()
formats and appends data to
.Fa dest. 
It mostly works like sprintf(), except that it appends data instead
of replacing existing data.
.PP
.Fa needs_max
is the maximum number of bytes that the formatted data will occupy,
.Fa fmt
is a standard printf() formatting string.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
