.TH cstring_pcat 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_pcat() \- Appends characters to a cstring
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.BI "status_t cstring_pcat(cstring dest, const char *start, const char *end);

.SH DESCRIPTION
Appends 0..n characters from start to end(exclusive).
.SH EXAMPLE
.in +4n
.nf
const char* hello = "Hello, world";
cstring s;
const char* end;
...
end = strchr(hello, ',');
cstring_pcat(s, hello, end); /* Appends "Hello" to s */
.nf
.in
