.TH cstring_split 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_split() \- Strip leading and trailing white space from a string.

Create an array of cstrings from a const char*, return the number
of items in the array. Each item must be freed separately.
delim can contain any number of characters, see strcspn()

.SH SYNOPSIS
.B #include <cstring.h>
.sp
.sp
.Fo "size_t cstring_split"
.Fa "cstring **dest"
.Fa "const char *src"
.Fa "const char *delim"
.Fc
.SH DESCRIPTION
.Nm
splits a string literal into multiple cstring strings. After successful
completion, the dest pointer will point to several cstring strings. The
exact number is returned as a return value.
.PP
Note that delim can be one or more characters, e.g. " \t\n" to split a
source string on either space, tab or newline characters.
.SH SEE ALSO
.Xr cstring_multifree 3
.SH EXAMPLE
.Bd -literal
.B #include <stdio.h>
.sp
.B #include <cstring.h>
.sp

int main(void)
{
	cstring *s;
	size_t i, n;

	n = cstring_split(&s, "Hello world", " ");
	for (i = 0; i < n; i++)
		printf("%s\n", c_str(s[i]));

	cstring_multifree(s, n);
	return 0;
}
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
