.TH cstring_left 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cstring_left()
.Nm cstring_right()
.Nd create a string from another string
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.BI "cstring cstring_left(cstring src, size_t n);

.BI "cstring cstring_right(cstring src, size_t n);

.SH DESCRIPTION
.Nm cstring_left()
creates a new cstring containing the 
.Fa n
leftmost characters of 
.Fa src.
.PP
.Nm cstring_right()
creates a new cstring containing the
.Fa n
rightmost characters of
.Fa src.
.PP
If 
.Fa n
is greater than the length of
.Fa src
, then the entire string will be copied.
.SH RETURN VALUE
Both functions return NULL if an error occurs, else a valid cstring. Remember to free the returned cstring using cstring_free().
.SH EXAMPLE
.in +4n
.nf
cstring h, w, s = cstring_new();
cstring_set(s, "Hello, World");

h = cstring_left(s, 5); /* h will contain "Hello" */
w = cstring_right(s, 5); /* w will contain "World" */

cstring_free(s);
cstring_free(h);
cstring_free(w);
.nf
.in
