.TH cstring_charcat 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_charcat() \- Append a character to a cstring
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.BI "int cstring_charcat(cstring dest, int c);

.SH DESCRIPTION
.Nm
appends the character
.Fa c
to the string
.Fa dest
 .
.SH RETURN VALUE
.Nm
returns 1 if the character was successfully appended to the
string
.Fa dest
, or 0 if 
.Nm
was unable to allocate memory.
.SH SEE ALSO
.Xr cstring_concat 3 ,
.Xr cstring_concat2 3 ,
.Xr cstring_concat3 3
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
