.TH cstring_upper 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_upper() \- Convert lower case to upper case letters.
.SH SYNOPSIS
.B #include <cstring.h>
.Fo "void cstring_upper"
.Fa "cstring s"
.Fc
.SH DESCRIPTION
.Nm
converts lower case letters to upper case letters.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
