.TH cstring_pcat 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_pcat() \- Appends characters to a cstring
.SH SYNOPSIS
.B #include <cstring.h>
.Fo "int cstring_pcat"
.Fa "cstring dest"
.Fa "const char *start"
.Fa "const char *end"
.Fc
.SH DESCRIPTION
Appends 0..n characters from start to end(exclusive).
.SH EXAMPLE
.Bd -literal
const char* hello = "Hello, world";
cstring s;
const char* end;
...
end = strchr(hello, ',');
cstring_pcat(s, hello, end); /* Appends "Hello" to s */
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
