.TH cstring_recycle 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cstring_recycle()
.Nd Clear contents of a cstring
.SH SYNOPSIS
.B #include <cstring.h>
.Fo "void cstring_recycle"
.Fa "cstring s"
.Fc
.SH DESCRIPTION
.Nm
removes the contents of the string
.Fa s. 
No memory will be freed and the string is fully usable after a call to
.Nm
, but will of course be empty.
.PP
The idea is to use this function instead of multiple calls to 
cstring_new()/cstring_free().
.SH EXAMPLE
.Bd -literal
size_t i, niter = 1000;
cstring s = cstring_new();
cstring_extend(s, 10000);
for(i = 0; i < niter; i++) {
	cstring_recycle(s); /* Remove contents from previous iteration */
	... /* Now use s for something */
}
cstring_free(s);
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
