.TH cstring_set 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm cstring_set()
.Nm cstring_nset()
.Nd Copy a string
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.BI "int cstring_set(cstring dest, const char* src);

.BI "int cstring_nset(cstring dest, const char* src, size_t n);

.SH DESCRIPTION
The
.Nm cstring_set()
function copies the string pointed to by
.Fa src
to the cstring pointed to by
.Fa dest.
.PP
The 
.Nm cstring_nset()
function is similar, except that not more than
.Fa n
bytes of 
.Fa src
are copied. The result will always be null-terminated.
.SH RETURN VALUE
Both functions return 1 if 
.Fa src
was successfully copied to 
.Fa dest,
or 0 if the functions failed to allocate memory.
.PP
.Nm cstring_nset()
copies at most
.Fa n
characters from
.Fa src
to
.Fa dest.
