.TH cstring_length 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_length() \- Calculate the length of a string
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.BI "size_t cstring_length(cstring s);

.SH DESCRIPTION
.Nm
calculates the length of the string 
.Fa s
, not including the terminating '\\0' character.
.SH RETURN VALUE
The 
.Nm
function returns the number of characters in 
.Nm
