.TH cstring_strip 3 2016-01-30 "" "The Meta C Library"
.SH NAME
cstring_strip() \- Strip leading and trailing white space from a string.
.SH SYNOPSIS
.B #include <cstring.h>
.sp
.Fo "void cstring_strip"
.Fa "cstring s"
.Fc
.SH DESCRIPTION
.Nm
strips leading and trailing white space from a string.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
