.TH fifo_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm fifo_new
.Nm fifo_free
.Nd A thread safe FIFO ADT.
.SH SYNOPSIS
.B #include <meta_fifo.h>
.Fo "fifo fifo_new"
.Fa "size_t nelem"
.Fc
.Fo "void fifo_free"
.Fa "fifo p"
.Fc
.SH DESCRIPTION
.Nm fifo_new()
creates a new fifo with room for nelem entries, and
.Fa foobar
.Nm fifo_free()
destroys a fifo created by 
.Nm fifo_new().
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
