.TH fifo_lock 3
.SH NAME
.Nm fifo_lock
.Nm fifo_unlock
.Nd Fifo access control
.SH SYNOPSIS
.Fd #include <meta_fifo.h>
.Fo "int fifo_lock"
.Fa "fifo p"
.Fc
.Fo "int fifo_unlock"
.Fa "fifo p"
.Fc
.SH DESCRIPTION
.Nm fifo_lock()
locks the fifo so that no other threads can access it.
.Nm fifo_unlock()
unlocks the fifo.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
