.TH fifo_free_slot_count 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm fifo_free_slot_count
.Nd Return the number of free slots in the fifo
.SH SYNOPSIS
.B #include <meta_fifo.h>
.Fo "size_t fifo_free_slot_count"
.Fa "fifo p"
.Fc
.SH DESCRIPTION
Return the number of free slots in the fifo
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
