.TH fifo_free_slot_count 3 2016-01-30 "" "The Meta C Library"
.SH NAME
fifo_free_slot_count \- Return the number of free slots in the fifo
.SH SYNOPSIS
.B #include <meta_fifo.h>
.sp
.BI "size_t fifo_free_slot_count(fifo p);

.SH DESCRIPTION
Return the number of free slots in the fifo
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
