.TH fifo_lock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm fifo_lock
.Nm fifo_unlock
.Nd Fifo access control
.SH SYNOPSIS
.B #include <meta_fifo.h>
.sp
.BI "int fifo_lock(fifo p);

.BI "int fifo_unlock(fifo p);

.SH DESCRIPTION
.Nm fifo_lock()
locks the fifo so that no other threads can access it.
.Nm fifo_unlock()
unlocks the fifo.
