.TH fifo_nelem 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm fifo_nelem
.Nd Returns the number of elements in the fifo.
.SH SYNOPSIS
.B #include <meta_fifo.h>
.Fo "size_t fifo_nelem"
.Fa "fifo p"
.Fc
.SH DESCRIPTION
Returns the number of elements in the fifo.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
