.TH filecache_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
filecache_new \- Short desc here
.SH SYNOPSIS
.BI "filecache filecache_new(size_t nelem, size_t bytes);

.SH DESCRIPTION
.Nm filecache_new()
Creates a new filecache.
nelem is used to presize a table of entries in the cache,
so that we can perform lookups faster than if using a
dynamic solution.
.PP
bytes are the total number of bytes the cache can use.
A megabyte is 1024*1024, btw.
nelem is the number of elements in the hash table(s),
and not the max number of elements in the cache.
