.TH filecache_new 3
.SH NAME
.Nm filecache_new
.Nd Short desc here
.SH SYNOPSIS
.Fo "filecache filecache_new"
.Fa "size_t nelem"
.Fa "size_t bytes"
.Fc
.SH DESCRIPTION
.Nm filecache_new()
Creates a new filecache.
nelem is used to presize a table of entries in the cache,
so that we can perform lookups faster than if using a
dynamic solution.
.Pp
bytes are the total number of bytes the cache can use.
A megabyte is 1024*1024, btw.
nelem is the number of elements in the hash table(s),
and not the max number of elements in the cache.
.SH AUTHOR
.An Bjorn Augestad bjorn.augestad@gmail.com
