.TH list_add 3 2016-01-30 "" "The Meta C Library"
.SH NAME
list_add() \- Add a new item to a list
.SH SYNOPSIS
.B #include <meta_list.h>
.sp
.Fo "list list_add"
.Fa "list lst"
.Fa "void* data"
.Fc
.SH DESCRIPTION
.Nm
adds a new node at the end of an existing list, or
creates a new list and adds data to the new list if lst is 
NULL. 
.PP
.Nm
will not copy the memory pointed to by data,
just the pointer itself. The memory should therefore be 
heap allocated
or static.
.SH RETURN VALUE
A pointer to lst if the new node was successfully 
added to the list, or NULL if list_add() failed to allocate 
memory.
.SH SEE ALSO
.Xr list_delete 3
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com.
