.TH get_basename 3 2016-01-30 "" "The Meta C Library"
.SH NAME
get_basename() \- get basename of a file name.
.SH SYNOPSIS
.B #include <highlander.h>
.sp
.BI "int get_basename(const char* name, const char* suffix, char* dest, size_t cb);

.SH DESCRIPTION
.Nm
is a replacement function for basename().
basename() is a SUSv2 function, but unfortunately it is not
commonly available on other platforms, e.g. cygwin. 
basename() is also a bit odd, so we replace it with our own version.
This function, get_basename(), mimics the basename(1) command, 
which accepts an optional suffix which will be stripped if provided.
.SH RETURN VALUE
.SH EXAMPLE
.Bd -literal
.Ed
.SH SEE ALSO
