.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th meta_convert 3
.Sh NAME
.Nm meta_convert
.Nd Conversion functions.
.Sh SYNOPSIS
.Fd #include <meta_convert.h>
.Fo "bool isint"
.Fa "const char *src"
.Fc
.Fo "bool isuint"
.Fa "const char *src"
.Fc
.Fo "bool islong"
.Fa "const char *src"
.Fc
.Fo "bool isulong"
.Fa "const char *src"
.Fc
.Fo "bool isfloat"
.Fa "const char *src"
.Fc
.Fo "bool isdouble"
.Fa "const char *src"
.Fc
.Sh DESCRIPTION
All of these functions return true if the src is of type int, uint and so forth.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
