.TH meta_convert 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm meta_convert
.Nd Conversion functions.
.SH SYNOPSIS
.B #include <meta_convert.h>
.Fo "bool isint"
.Fa "const char *src"
.Fc
.Fo "bool isuint"
.Fa "const char *src"
.Fc
.Fo "bool islong"
.Fa "const char *src"
.Fc
.Fo "bool isulong"
.Fa "const char *src"
.Fc
.Fo "bool isfloat"
.Fa "const char *src"
.Fc
.Fo "bool isdouble"
.Fa "const char *src"
.Fc
.SH DESCRIPTION
All of these functions return true if the src is of type int, uint and so forth.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
