.TH meta_convert 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_convert \- Conversion functions.
.SH SYNOPSIS
.B #include <meta_convert.h>
.sp
.BI "bool isint(const char *src);

.BI "bool isuint(const char *src);

.BI "bool islong(const char *src);

.BI "bool isulong(const char *src);

.BI "bool isfloat(const char *src);

.BI "bool isdouble(const char *src);

.SH DESCRIPTION
All of these functions return true if the src is of type int, uint and so forth.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
