.TH list_get 3
.SH NAME
.Nm list_get() 
.Nd Return a pointer to a node in a list.
.SH SYNOPSIS
.Fd #include <meta_list.h>
.Fo "void* list_get"
.Fa "list_iterator i"
.Fc
.SH DESCRIPTION
.Nm
returns a pointer to an item in the list. 
.SH SEE ALSO
.Xr list_add 3 
.Xr list_get_item 3 
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
