.TH list_remove_node 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm list_remove_node() 
.Nd Remove a node from a list.
.SH SYNOPSIS
.B #include <meta_list.h>
.Fo "list_iterator list_remove_node"
.Fa "list lst"
.Fa "list_iterator i"
.Fc
.br
.SH DESCRIPTION
.Nm
removes one node from the list, but does NOT free the data memory.
Use with care, and use list_delete() instead if the intention was to free
the memory as well.
.SH SEE ALSO
.Xr list_delete 3
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
