.TH list_merge 3 2016-01-30 "" "The Meta C Library"
.SH NAME
list_merge() \- merges two lists.
.SH SYNOPSIS
.B #include <meta_list.h>
.Fo "list list_merge"
.Fa "list dest"
.Fa "list src"
.Fc
.SH DESCRIPTION
.Nm
merges two lists into one list. 
Sometimes we need to merge two lists. Data from both lists will 
be added to the new list. We will not check for duplicates or anything else. 
.Fa src
will be invalid after the merge. You don't have to free 
.Fa src
, 
.Nm 
will do that for you.
.SH RETURN VALUE
.Nm
returns a pointer to 
.Fa dest
or NULL if anything went wrong.
.Fa dest
can be NULL, 
.Fa src
cannot. If the 
.Fa dest
pointer is NULL, then
.Nm
returns a pointer to a new list if no error occurs.
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
