.TH list_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm list_new() 
.Nm list_free() 
.Nd Create and destroy lists
.SH SYNOPSIS
.B #include <meta_list.h>
.sp
.BI "list list_new(void);

.BI "void list_free(list lst, dtor dtor);

.SH DESCRIPTION
.Nm list_new()
creates a new list, returns NULL if failure. 
.Nm list_free()
frees a list.
.Fa dtor 
is a pointer an optional cleanup function which is called once
for each node in the list. If 
.Fa dtor
is NULL, then the data will not be freed.
.SH EXAMPLE
.in +4n
.nf
/* The object we store in the list */
struct foo {
    char *name;
};

/* Destructor for foo */
void foo_dtor(void* arg)
{
    struct foo* p = arg;
    if(p != NULL) {
        free(p->name);
        free(p);
    }
}
\&...
list lst = list_new();
\&...
list_free(lst, foo_dtor);
.nf
.in
