.TH list_next 3 2016-01-30 "" "The Meta C Library"
.SH NAME
list_next() \- Move to the next node in a list.
.SH SYNOPSIS
.B #include <meta_list.h>
.Fo "list_iterator list_next"
.Fa "list_iterator i"
.Fc
.SH DESCRIPTION
.Nm 
returns an iterator to the next item. 
.SH EXAMPLE
.Bd -literal
list lst;
list_iterator i;
\&...
for(i = list_first(lst); !list_end(i); i = list_next(i)) {
	...
}
.Ed
.SH SEE ALSO
.Xr list_first 3 ,
.Xr list_end 3
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
