.TH list_insert 3
.SH NAME
.Nm list_insert() 
.Nd Insert a node in front of the list.
.SH SYNOPSIS
.Fd #include <meta_list.h>
.Fo "list list_insert"
.Fa "list lst"
.Fa "void *data"
.Fc
.SH DESCRIPTION
.Nm
insert a new node in the front of the list.  returns NULL if we fail. 
.Nm
will allocate a new list if lst is NULL.
.SH SEE ALSO
.Xr list_add() 3
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
