.TH list_count 3 2016-01-30 "" "The Meta C Library"
.SH NAME
list_count() \- Count the number of nodes satisfying some criteria.
.SH SYNOPSIS
.B #include <meta_list.h>
.sp
.BI "size_t list_count(list lst, int (*include_node)(void*));

.SH DESCRIPTION
.Nm
counts the number of nodes in the list which complies to some criteria. The criteria is decided by a caller supplied
function. That function should return 1 if the node is to be counted, and 0 if the node is not to be counted.  Use NULL as function parameter if you want to count all items.
