.TH list_sort 3 2016-01-30 "" "The Meta C Library"
.SH NAME
list_sort() \- Sort a list
.SH SYNOPSIS
.B #include <meta_list.h>
.sp
.BI "void list_sort(list " lst ", int(*" compar ")(const void *p1, const void *p2));

.SH DESCRIPTION
.BR list_sort()
sorts a list, but is probably very slow.
.PP
The contents of the list are sorted in ascending order according to a comparison function pointed to by
compar, which is called with two arguments that point to the objects being compared.
.PP
The comparison function must return an integer less than, equal to, or greater than zero if the
first argument is considered to be respectively less than, equal to, or greater than the second
argument. 
