.TH list_get_item 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm list_get_item() 
.Nd Return a node.
.SH SYNOPSIS
.B #include <meta_list.h>
.Fo "void* list_get_item"
.Fa "list lst"
.Fa "size_t index"
.Fc
.SH DESCRIPTION
.Nm
returns the n'th node in the list, or NULL if 
.Fa index
is out of bounds.
.Fa index
is zero based, so the value 0 will return the first item.
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
