.TH list_first 3
.SH NAME
.Nm list_first() 
.Nd Return an iterator to the first node in a list.
.SH SYNOPSIS
.Fd #include <meta_list.h>
.Fo "list_iterator list_first"
.Fa "list lst"
.Fc
.SH DESCRIPTION
.Nm
returns an iterator to the first item. Use list_end() to test if we reached the end 
of the list, i.e. the list was empty.
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
