.TH meta_process 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_process \- Process management ADT
.SH SYNOPSIS
.B #include <meta_process.h>
.sp
.BI "process process_new);

.BI "void process_free(process p);

.BI "int process_shutting_down(process p);

.BI "int process_set_rootdir(process p, const char *path);

.BI "int process_set_username(process p, const char *username);

.BI "int process_add_object_to_start(process p, void *object, int do_func(void *), int undo_func(void *), int run_func(void *), int shutdown_func(void *));

.BI "int process_start(process p, int fork_and_close);

.BI "int process_wait_for_shutdown(process p);

.BI "int process_get_exitcode(process p, void *object);

.SH DESCRIPTION
A process object is used to control the currently executing process.
Normally the process consists of one or more http_server threads.
These threads cannot change e.g. current directory as that will 
affect other threads as well. They cannot change user id
(of course they can, but the http servers are just threads 
in a process not the process itself).
.PP
The process ADT controls current directory, shutdown semantics,
startup semantics and more. 
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
