.TH meta_array 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_array \- Dynamic array ADT
.SH SYNOPSIS
.B #include <meta_array.h>
.sp
.Fo "array array_new"
.Fa "size_t nmemb"
.Fa "int can_grow"
.Fc
.Fo "void array_free"
.Fa "array p"
.Fa "dtor cleanup"
.Fc
.Fo "int array_nelem"
.Fa "array p"
.Fc
.Fo "int array_extend"
.Fa "array p"
.Fa "size_t nelem"
.Fc
.Fo "int array_get"
.Fa "array p "
.Fa "size_t i"
.Fc
.Fo "int array_add"
.Fa "array p"
.Fa "void *elem"
.Fc
.SH DESCRIPTION
An array stores n elements of void* pointers. The pointers should not
point to automatic memory.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
