.TH meta_cache 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_cache \- A cache ADT
.SH SYNOPSIS
.B #include <meta_cache.h>
.sp
.BI "cache cache_new(size_t nelem, size_t hotlist_nelem, size_t bytes);

.BI "void cache_free(cache c, dtor cleanup);

.BI "int cache_add(cache c, size_t id, void *data, size_t cb, int pin);

.BI "int cache_exists(cache c, size_t id);

.BI "int cache_get(cache c, size_t id, void **pdata, size_t *pcb);

.BI "int cache_remove(cache c, size_t id);

.SH DESCRIPTION
A meta_cache is just a simple cache to which you can add and later
retrieve items. 
.PP
An item is any number of bytes identified by an id.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
