.TH meta_atomic 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_atomic \- Atomic types and operators
.SH SYNOPSIS
.B #include <meta_atomic.h>
.sp
.BI "void atomic_X_init(atomic_X *p);

.BI "void atomic_X_destroy(atomic_X *p);

.BI "X atomic_X_get(atomic_X *p);

.BI "void atomic_X_set(atomic_X *p);
.Fa "X value"

.BI "X atomic_X_add(atomic_X *p);
.Fa "X value"

.BI "void atomic_X_inc(atomic_X *p);

.BI "void atomic_X_dec(atomic_X *p);

.SH DESCRIPTION
The core meta library provides atomic versions of many integer data types,
as well as operators to manipulate the values.
.PP
When writing multithreaded applications, it's important that two threads
don't change the same variable at the same time. The atomic types
can be changed and read in a thead safe way, eliminating the need for
explicit locking of variables.
.PP
This module provides atomic versions of uint16_t, uint32_t, int, unsigned long,
and unsigned long long.  These types are named atomic_u16, atomic_u32, 
atomic_int, atomic_ulong and atomic_ull.
.PP
Type safe versions of all functions are provided and the data type is
a part of the function name. 
.PP
The methods provided are atomic_X_init(), atomic_X_destroy(), atomic_X_get(),
atomic_X_set(), atomic_X_add(), atomic_X_inc() and atomic_X_dec(). X indicates
where in the function name the data type is placed. Replace X with either
ull, ulong, u16, u32 or int. For example, the u32 atomic data type will have
functions named atomic_u32_init(), atomic_u32_destroy(), atomic_u32_get(),
atomic_u32_set(), atomic_u32_add(), atomic_u32_inc() and atomic_u32_dec().
.PP
.Nm 
also provides an ATOMIC_INITIALIZER literal, which can be used to initialize
objects, just like PTHREAD_MUTEX_INITIALIZER initialize mutexes.
.PP
To use an atomic type, you must first call atomic_X_init() or 
use ATOMIC_INITIALIZER. Remember to call atomic_X_destroy() if you called 
atomic_X_init().
.PP
Note that atomic_X_add(), atomic_X_inc() and atomic_X_dec() returns
the value of the atomic type after your modification, but before the object
is unlocked. 
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
