.TH meta_array 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_array \- Dynamic array ADT
.SH SYNOPSIS
.B #include <meta_array.h>
.sp
.BI "array array_new(size_t nmemb, int can_grow);

.BI "void array_free(array p, dtor cleanup);

.BI "int array_nelem(array p);

.BI "int array_extend(array p, size_t nelem);

.BI "int array_get(array p, size_t i);

.BI "int array_add(array p, void *elem);

.SH DESCRIPTION
An array stores n elements of void* pointers. The pointers should not
point to automatic memory.
