.TH pool_add 3 2016-01-30 "" "The Meta C Library"
.SH NAME
pool_add \- Object management ADT
.SH SYNOPSIS
.B #include <meta_pool.h>
.sp
.Fo "void* pool_add"
.Fa "pool p"
.Fa "void *resource"
.Fc
.SH DESCRIPTION
Adds a new resource to the resource pool. 
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
