.TH pool_recycle 3 2016-01-30 "" "The Meta C Library"
.SH NAME
pool_recycle \- Object management ADT
.SH SYNOPSIS
.B #include <meta_pool.h>
.sp
.BI "void* pool_recycle(pool p, void *resource);

.SH DESCRIPTION
Returns a resource to the pool. You should always return a resource to the
pool as soon as possible, so that other threads may use the same resource.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
