.TH pool_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm pool_new
.Nm pool_free
.Nd Object management ADT
.SH SYNOPSIS
.B #include <meta_pool.h>
.Fo "pool pool_new"
.Fc
.Fo "void pool_free"
.Fa "pool p"
.Fa "dtor cleanup"
.Fc
.SH DESCRIPTION
Creates a new resource pool. The pool will have room for nelem elements.
A resource pool is nice to have if you want to preallocate/precreate
objects and then later use them. The pool ADT is thread safe.
.PP
pool p;
...
if( (p = pool_new(NELEM)) != NULL) {
   for(i = 0; i < NELEM; i++) {
       my_resource mr = create_my_resource();
       pool_add(p, mr);
   }
my_resource mr = pool_get(p);
... 
pool_recycle(p, mr);
pool_free(p, (dtor)destroy_my_resource);
.PP
.Nm pool_free frees the pool and all entries in it.
The entries in the pool will not be freed if the cleanup 
function pointer parameter is NULL,
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

