.TH process_get_exitcode 3 2016-01-30 "" "The Meta C Library"
.SH NAME
process_get_exitcode() \- Get exit code from a thread
.SH SYNOPSIS
.B #include <meta_process.h>
.sp
.Fo "int process_get_exitcode"
.Fa "process p"
.Fa "void* object"
.Fc
.SH DESCRIPTION
.Nm
Returns the exit code from the objects run() function. 
It will return -1 for any invalid pointers to object.
.Fa object
is used to locate a previously added object.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
