.TH process_shutting_down 3
.SH NAME
.Nm process_shutting_down()
.Nd Is the process shutting down?
.SH SYNOPSIS
.Fd #include <meta_process.h>
.Fo "int process_shutting_down"
.Fa "process p"
.Fc
.SH DESCRIPTION
.Nm
returns 1 if the process has received SIGTERM, 0 if not.
Since process_start() returns after it has started all objects,
you might want to do other things in the "main" thread. These other
things must have a way of stopping processing when the process 
shuts down.
.SH SEE ALSO
.Xr process_wait_for_shutdown 3
.SH EXAMPLE
.Bd -literal
process p = process_new();
/* Register objects to start */
\&...
process_start(p, 1);
while(!process_shutting_down(p)) {
	printf("Still not received SIGTERM...\n");
	sleep(1);
}
process_free(p);
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
