.TH process_wait_for_shutdown 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm process_wait_for_shutdown()
.Nd process_wait_for_shutdown
.SH SYNOPSIS
.B #include <meta_process.h>
.sp
.BI "int process_wait_for_shutdown(process p);

.SH DESCRIPTION
Wait for shutdown is needed to avoid that we fall off main().
.Nm
just joins the shutdown thread.
.SH EXAMPLE
.in +4n
.nf
process p = process_new();
\&...
process_start(p, 1);
process_wait_for_shutdown();
process_free(p);
.nf
.in
