.TH process_shutting_down 3 2016-01-30 "" "The Meta C Library"
.SH NAME
process_shutting_down() \- Is the process shutting down?
.SH SYNOPSIS
.B #include <meta_process.h>
.sp
.BI "int process_shutting_down(process p);

.SH DESCRIPTION
.Nm
returns 1 if the process has received SIGTERM, 0 if not.
Since process_start() returns after it has started all objects,
you might want to do other things in the "main" thread. These other
things must have a way of stopping processing when the process 
shuts down.
.SH SEE ALSO
.BR process_wait_for_shutdown 3
.SH EXAMPLE
.in +4n
.nf
process p = process_new();
/* Register objects to start */
\&...
process_start(p, 1);
while(!process_shutting_down(p)) {
    printf("Still not received SIGTERM...\n");
    sleep(1);
}
process_free(p);
.nf
.in
