.TH process_set_rootdir 3 2016-01-30 "" "The Meta C Library"
.SH NAME
process_set_rootdir() \- Set root directory for a process object
.SH SYNOPSIS
.B #include <meta_process.h>
.sp
.Fo "int process_set_rootdir"
.Fa "process p"
.Fa "const char* path"
.Fc
.SH DESCRIPTION
Stores the path to the directory which will be the 
"root directory" when the process_start() function
returns. It will also change the current directory
to the root dir.
.PP
The process_start() function will not change the root
directory of the process unless process_set_rootdir()
has been called.
.PP
Note that you have to be root to change root directory
for a process. 
.SH RETURN VALUE
.Nm
returns 1 on success and 0 if an error occurs.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
