.TH sock_write 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sock_write \- Write data to socket.
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.Fo "int sock_write"
.Fa "meta_socket p"
.Fa "const char *s"
.Fa "size_t count"
.Fa "int timeout"
.Fa "int retries"
.Fc
.SH DESCRIPTION
.Nm
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
