.TH sock_set_nonblock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm sock_set_nonblock
.Nd Make the socket non-blocking
.SH SYNOPSIS
.B #include <meta_sock.h>
.Fo "int sock_set_nonblock"
.Fa "meta_socket p"
.Fc
.SH DESCRIPTION
.Nm
makes the socket non-blocking.
.SH SEE ALSO
.Xr sock_clear_nonblock 3
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
