.TH sock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm sock
.Nd sock
.SH SYNOPSIS
.B #include <meta_sock.h>
.SH DESCRIPTION
Utility functions for sockets

NOTE: This file is just a collection of utility functions manipulating
sockets. It's not a proper adt. Even a bug or two exist, and the
return codes are very inconsistent. All of this means that sock.[ch]
is up for a redesign/rewrite.
(BTW: the known bug is gethostname() instead of gethostname_r() in
reentrant programs).
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
