.TH sock_set_nonblock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sock_set_nonblock \- Make the socket non-blocking
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.BI "int sock_set_nonblock(meta_socket p);

.SH DESCRIPTION
.Nm
makes the socket non-blocking.
.SH SEE ALSO
.Xr sock_clear_nonblock 3
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
