.TH sock_close 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm sock_close
.Nd Close a socket
.SH SYNOPSIS
.B #include <meta_sock.h>
.Fo "int sock_close"
.Fa "meta_socket p"
.Fc
.SH DESCRIPTION
Closes the socket.
.Nm
sock_close first calls shutdown() with the how parameter set to
SHUT_RDWR. Then it closes the socket using close().
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
