.TH sock_read 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sock_read \- Read data off a socket.
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.BI "int sock_read(meta_socket p, char *buf, size_t cbMax, int timeout, int retries, size_t* cbReadSum);

.SH DESCRIPTION
.Nm
reads up to and including cbMax bytes off the socket, if that
count is available.
.Nm
will retry the operation nretries times and call wait_for_data()
to wait for data to arrive on the socket. If no data is available
within the number of retries times the timeout period, then
the function will return 0.
