.TH sock_socket 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sock_socket \- Create a new meta_socket
.SH SYNOPSIS
.B #include <meta_sock.h>
.Fo "meta_socket sock_socket"
.Fa "int unix_socket"
.Fc
.SH DESCRIPTION
.Nm
Creates a new socket.
This is a wrapper function for a call to socket().
If unix_socket is !0, then a UNIX socket is created, else
an INET socket is created.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
