.TH sock_accept 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sock_accept \- Y
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.Fo "meta_socket sock_accept"
.Fa "meta_socket p"
.Fa "struct sockaddr *addr"
.Fa "socklen_t *addrsize"
.Fc
.SH DESCRIPTION
.Nm
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
