.TH sock_bind 3
.SH NAME
.Nm sock_bind
.Nd Y
.SH SYNOPSIS
.Fd #include <meta_sock.h>
.Fo "int sock_bind"
.Fa "meta_socket p"
.Fa "const char *hostname"
.Fa "int port"
.Fc
.SH DESCRIPTION
.Nm
binds a socket to a host/port combo. Returns 0 if an error occured,
and 1 if the operation was successful.
.SH SEE ALSO
.Xr bind 2
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
