.TH sock_clear_nonblock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sock_clear_nonblock \- Y
.SH SYNOPSIS
.B #include <meta_sock.h>
.sp
.BI "int sock_clear_nonblock(meta_socket p);

.SH DESCRIPTION
.Nm
clears the O_NONBLOCK flag from the socket. This means that
read/write operations on the socket will block after this 
function is called.
.SH SEE ALSO
.BR sock_set_nonblock 3
