.Dd Nov 29, 2014
.Os POSIX
.Dt SOCK
.Th sock_close 3
.Sh NAME
.Nm sock_close
.Nd Close a socket
.Sh SYNOPSIS
.Fd #include <meta_sock.h>
.Fo "int sock_close"
.Fa "meta_socket p"
.Fc
.Sh DESCRIPTION
Closes the socket.
.Nm
sock_close first calls shutdown() with the how parameter set to
SHUT_RDWR. Then it closes the socket using close().
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
