.TH sublist_free 3
.SH NAME
.Nm sublist_free() 
.Nd Free a sublist.
.SH SYNOPSIS
.Fd #include <meta_list.h>
.Fo "void sublist_free"
.Fa "list lst"
.Fc
.SH DESCRIPTION
.Nm
frees all memory used by the sublist, but does not free the nodes in the list. 
Use 
.Nm
to free lists created by sublist_copy, sublist_create(), sublist_create_neg() and sublist_adaptor().
.SH SEE ALSO
.Xr sublist_copy 3 ,
.Xr sublist_create 3 ,
.Xr sublist_create_neg 3 ,
.Xr sublist_adaptor 3
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
