.TH sublist_free 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sublist_free() \- Free a sublist.
.SH SYNOPSIS
.B #include <meta_list.h>
.sp
.BI "void sublist_free(list lst);

.SH DESCRIPTION
.Nm
frees all memory used by the sublist, but does not free the nodes in the list. 
Use 
.Nm
to free lists created by sublist_copy, sublist_create(), sublist_create_neg() and sublist_adaptor().
.SH SEE ALSO
.Xr sublist_copy 3 ,
.Xr sublist_create 3 ,
.Xr sublist_create_neg 3 ,
.Xr sublist_adaptor 3
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
