.TH sublist_copy 3 2016-01-30 "" "The Meta C Library"
.SH NAME
sublist_copy() \- Copy a list, but not the data.
.SH SYNOPSIS
.B #include <meta_list.h>
.sp
.Fo "list sublist_copy"
.Fa "list lst"
.Fc
.SH DESCRIPTION
.Nm
creates a copy of the list
.Fa lst,
but does not copy the data itself. This function is nice to have if
you have a list in a specific order and don't want to change that
list, but still want fo e.g. sort a copy of the list in a different
order without copying the data. 
Free it with sublist_free.
.SH SEE ALSO
.Xr sublist_free 3
.SH AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
