.TH tcp_server_free_root_resources 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_free_root_resources() \- tcp_server_free_root_resources
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "int tcp_server_free_root_resources(tcp_server s);

.SH DESCRIPTION
Does the opposite of get_root_resources(). It will typically
close the socket in use.
.SH EXAMPLE
.in +4n
.nf
.nf
.in
