.TH tcp_server_allow_clients 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_allow_clients() \- Set client filter
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "int tcp_server_allow_clients(tcp_server srv, const char* filter);

.SH DESCRIPTION
.Nm
sets a filter which will be used to deny clients access
to the tcp server. The filter can be a regular expression,
but cannot contain DNS names. DNS names are denied to
avoid the risk of DNS spoofing, as well as to increase performance.
The idea is that normally you do not want filtering, in the cases
you do, the number of clients allowed is relatively small.
.PP
The regexp can be anything, but should contain IP addresses
to work. The number of addresses specified is only limited
by your platforms implementation of regcomp. 
.SH RETURN VALUE
.Nm
returns 1 on success, 0 on errors. Note that errno may be a bit odd as regcomp() has special error codes which this function will return.
.SH EXAMPLE
.in +4n
.nf
   const char *filter = "1.1.1.* 2.*.1.? 192.168.*.*";
   tcp_server_allow_clients(srv, filter);
.nf
.in
.SH SEE ALSO
.BR regcomp tcp_server_clear_client_filter
