.TH tcp_server_shutting_down 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_shutting_down() \- Is the tcp_server shutting down?
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "int tcp_server_shutting_down(tcp_server srv);

.SH DESCRIPTION
.Nm
returns 1 if we're shutting down, 0 if we're not. Call this function
from your own service functions to be able to tell when to terminate
if your connections tend to be long.
.SH EXAMPLE
Here we call 
.Nm
to check for shutdown. Whenever 
.Nm
returns 1, we stop echoing characters and return, effectively
terminating the connection.
.Bd -literal
.B #include <tcp_server.h>
.sp
.B #include <connection.h>
.sp
void* echoserverfn(void* arg)
{
	int c;
	connection conn = arg;
	tcp_server s = connection_arg2(conn);
	while(!tcp_server_shutting_down(s) 
	&& connection_getc(conn, &c)) {
		connection_putc(conn, c);
		connection_flush(conn);
	}
	return NULL;
}
int main(void)
{
	tcp_server s = tcp_server_new();
	tcp_server_set_service_function(
		s, 
		echoserverfn,
		s);
	tcp_server_init(s);
	tcp_server_get_root_resources(s);
	tcp_server_start(s);
	tcp_server_free(s);
	return 0;
}
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
