.TH tcp_server_shutdown 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm tcp_server_shutdown()
.Nd Stop a tcp_server
.SH SYNOPSIS
.B #include <tcp_server.h>
.Fo "void tcp_server_shutdown"
.Fa "tcp_server srv"
.Fc
.SH DESCRIPTION
.Nm
stops the TCP server, causing 
.Nm tcp_server_start()
to return. This function is often called from a separate thread
when the process receives SIGTERM.
.PP
Shutdown is an ansynchronus operation and the server threads 
will run for some time after tcp_server_shutdown returns. How long
depends on the timeout values used.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
