.TH tcp_server_set_block_when_full 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_block_when_full() \- Set blocking behaviour
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.Fo "void tcp_server_set_block_when_full"
.Fa "tcp_server srv"
.Fa "int block"
.Fc
.SH DESCRIPTION
The tcp_server can either block when the queue is full, or just
discard the request. The default behaviour is to discard the 
connection request if the work queue is full, but this can be
changed using this function.
.Fa block
must be either 0 or 1.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
