.TH tcp_server_set_retries 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm tcp_server_set_retries()
.Nd 
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "void tcp_server_set_retries(tcp_server srv, int reads, int writes);

.SH DESCRIPTION
Set the number of retries that will be performed when reading or 
writing. 0 is a valid value, as the tcp_server will try once,
and retry from 0 to n times.
.PP
A low timeout value and a high retry value will create a snappy server,
but will consume resources. A reasonable timeout value and a retry
of 0, will consume the least resources, but will make shutdown 
slower as the process will wait until the read attempts times out.
.SH SEE ALSO
.Xr tcp_server_new() 3
.Xr tcp_server_init() 3
