.TH tcp_server_clear_client_filter 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm Clears the client filter for a tcp_server
.Nd 
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.Fo "void tcp_server_clear_client_filter"
.Fa "tcp_server srv"
.Fc
.SH DESCRIPTION
Clears any previously added client filter.
.SH SEE ALSO
.Xr tcp_server_allow_clients
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
