.TH tcp_server_set_port 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm tcp_server_set_port()
.Nd Set the port number to listen on.
.SH SYNOPSIS
.B #include <tcp_server.h>
.Fo "void tcp_server_set_port"
.Fa "tcp_server srv"
.Fa "int port"
.Fc
.SH DESCRIPTION
Sets the port number that the tcp_server will listen to.
The tcp_server will by default listen to port 2000. Listening to
ports below 1024 requires that root starts the process.
.SH SEE ALSO
.Xr process tcp_server_get_root_resources 3
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
