.TH tcp_server_set_queue_size 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_queue_size() \- Set size of work queue.
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "void tcp_server_set_queue_size(tcp_server srv, size_t size);

.SH DESCRIPTION
Sets the size of the work queue. The main thread in the tcp_server
accepts connection requests and puts these requests in a queue which
the worker threads reads from. 
.PP
.SH SEE ALSO
.Xr tcp_server_set_block_when_full 3 ,
.Xr tcp_server_set_worker_threads 3
.Ed
