.TH tcp_server_new 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm tcp_server_new()
.Nm tcp_server_free()
.Nd Create and destroy tcp_server objects
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "tcp_server tcp_server_new(void);

.BI "void tcp_server_free(tcp_server srv);

.SH DESCRIPTION
.Nm tcp_server_new()
creates a new instance of a tcp_server.
The new instance will set up default values for the 
tcp_server. You can override these defaults later, but it has
to be done before the tcp_server is started.
.Bd -literal
Timeout reads           : 5 seconds
Timeout writes          : 1 second
Timeout accepts         : 8 seconds
Retries reads           :  0
Retries writes          : 10
Connection queue size   : 200
Number of worker threads: 10
Port number to listen to: 2000
Device to listen to     : any
Who can connect         : All IP addresses
Read buffer size        :  4 KB
Write buffer size       : 64 KB
Block when full         : No
.Ed
.PP
.Nm tcp_server_free()
Frees all memory and all resources used by the tcp_server.
The server cannot be used after a call to tcp_server_free().
.SH EXAMPLE
.Bd -literal
tcp_server s = tcp_server_new();
\&...
tcp_server_free(s);
.Ed
