.TH tcp_server_set_readbuf_size 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_readbuf_size() \- tcp_server_set_readbuf_size
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "void tcp_server_set_readbuf_size(tcp_server s, size_t size);

.SH DESCRIPTION
Sets the size of the read buffer.
Incoming data is buffered for each connection. The size of
the buffer can be set prior to the call to tcp_server_init().
The default value is 4 KB, but you can set it to any reasonable
value.
.BR connection_new() 3 ,
.BR tcp_server_new() 3 ,
.BR tcp_server_set_writebuf_size() 3 ,
.BR tcp_server_init() 3 
