.TH tcp_server_init 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_init() \- Initialize a tcp_server object
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "int tcp_server_init(tcp_server srv);

.SH DESCRIPTION
.Nm
creates a thread pool which will be used as worker threads,
and creates all connection objects.
.PP
The idea is that the caller first can create a tcp_server
using tcp_server_new(). Then the user can configure the 
tcp_server and finally initialize it using this function.
.SH RETURN VALUE
.Nm
returns 1 on success, else 0.
.SH EXAMPLE
.in +4n
.nf
tcp_server srv = tcp_server_new();
tcp_server_set_worker_threads(srv, 80);
tcp_server_init(srv);
.nf
.in
