.TH tcp_server_set_port 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_port() \- Set the port number to listen on.
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "void tcp_server_set_port(tcp_server srv, int port);

.SH DESCRIPTION
Sets the port number that the tcp_server will listen to.
The tcp_server will by default listen to port 2000. Listening to
ports below 1024 requires that root starts the process.
.SH SEE ALSO
.BR process tcp_server_get_root_resources 3
