.TH tcp_server_free_root_resources 3
.SH NAME
.Nm tcp_server_free_root_resources()
.Nd tcp_server_free_root_resources
.SH SYNOPSIS
.Fd #include <tcp_server.h>
.Fo "int tcp_server_free_root_resources"
.Fa "tcp_server s"
.Fc
.SH DESCRIPTION
Does the opposite of get_root_resources(). It will typically
close the socket in use.
.SH EXAMPLE
.Bd -literal
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
