.TH tcp_server_start_via_process 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_start_via_process() \- Let the process ADT start the tcp_server
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "int tcp_server_start_via_process(process p, tcp_server s);

.SH DESCRIPTION
Let the process ADT start the tcp server instead of starting it
ourselves. The process ADT handles proper startup and shutdown
and 
.Nm
is a utility function to register a tcp_server object 
with a process object.
.SH SEE ALSO
.Xr meta_process 7 ,
.Xr process_start 3 ,
.Xr process_add_object_to_start 3 
.SH EXAMPLE
.in +4n
.nf
.B #include <meta_process.h>
.sp
.B #include <tcp_server.h>
.sp
.B #include <connection.h>
.sp
void* echoserverfn(void* arg)
{
	int c;
	connection conn = arg;
	tcp_server s = connection_arg2(conn);
	while(!tcp_server_shutting_down(s) 
	&& connection_getc(conn, &c)) {
		connection_putc(conn, c);
		connection_flush(conn);
	}
	return NULL;
}
int main(void)
{
	process p = process_new("echoserver");
	tcp_server s = tcp_server_new();
	tcp_server_set_service_function(
		s, 
		echoserverfn,
		s);
	tcp_server_init(s);
	tcp_server_start_via_process(p, s);
	process_start(p, 0);
	process_wait_for_shutdown(p);
	
	tcp_server_free(s);
	process_free(p);
	return 0;
}
.nf
.in
