.TH tcp_server_set_hostname 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_hostname() \- Set host name for the tcp_server
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "int tcp_server_set_hostname(tcp_server srv, const char* host);

.SH DESCRIPTION
.Nm
sets the host name for the tcp server.  
.PP
The server will bind to this hostname. You can set it to NULL
if you want to clear a previously assigned host name. The content
of the host parameter will be copied and stored within the tcp_server,
so any string will do as an argument.
.SH EXAMPLE
.Bd -literal
tcp_server s = tcp_server_new();
/* Listen to localhost only */
tcp_server_set_nostname(s, "localhost");
\&...
tcp_server_free(s);
.Ed
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
