.TH tcp_server_set_timeout 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_timeout() \- Sets timeout values for a tcp_server
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "void tcp_server_set_timeout(tcp_server srv, int reads, int writes, int accepts);

.SH DESCRIPTION
.Nm
sets the number of seconds to wait when reading or writing to 
the socket, as well as the time to wait when accepting new 
connections. 
.PP
The tcp_server uses poll() to see if data is available on a socket,
or to see if it is possible to write data to a socket. poll() will
wait for
.Fa reads
and 
.Fa writes
seconds before it tries to read or write data from/to the socket.
If no data is available it will retry the operation.
.PP
The 
.Fa accepts
parameter affects how fast the server responds to
a shutdown request. If the value is set very high and a shutdown
is requested, the server will not stop servicing connections until
the accept() call (poll() actually) times out. On average that time
will be half of the value in accepts. The default value is 8
seconds, which means that the server on average will respond to
the shutdown request after 4 seconds. If you set it too low, you
will consume more system resources(cpu) than you have to.
.SH SEE ALSO
.Xr tcp_server_set_retries() 3
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
