.TH tcp_server_set_writebuf_size 3 2016-01-30 "" "The Meta C Library"
.SH NAME
tcp_server_set_writebuf_size() \- Sets size of buffer for outgoing data
.SH SYNOPSIS
.B #include <tcp_server.h>
.sp
.BI "void tcp_server_set_writebuf_size(tcp_server s, size_t size);

.SH DESCRIPTION
.Nm
Sets the size of the write buffer.
Outgoing data is buffered for each connection. The size of
the buffer can be set prior to the call to tcp_server_init().
The default value is 64 KB, but you can set it to any reasonable
value.
.SH SEE ALSO
.BR tcp_server_set_readbuf_size 3
