.TH td2p 3 2016-01-30 "" "The Meta C Library"
.SH NAME
td2p() \- td2p
.SH SYNOPSIS
.B #include <highlander.h>
.sp
.BI "int td2p(http_response response, const char* text);

.SH DESCRIPTION
We want to keep the executable small, we therefore use functions for
some common tasks instead of spreading a lot of constant data around
in the application. This will make the app a bit slower, but we can 
live with that until gprof tells us otherwise.
.PP
Adds a <TD>text</TD> to the page 
int td2p(http_response response, const char* text);
.SH RETURN VALUE
.SH EXAMPLE
.Bd -literal
.Ed
.SH SEE ALSO
