.TH meta_convert 3 2016-01-30 "" "The Meta C Library"
.SH NAME
meta_convert \- Conversion functions.
.SH SYNOPSIS
.B #include <meta_convert.h>
.sp
.BI "status_t toint(const char *src, int *dest);

.BI "status_t touint(const char *src, unsigned int *dest);

.BI "status_t tolong(const char *src, long *dest);

.BI "status_t toulong(const char *src, unsigned long *dest);

.BI "status_t tofloat(const char *src, float *dest);

.BI "status_t todouble(const char *src, double *dest);

.SH DESCRIPTION
All of these functions convert a string to a number. They all return success or
failure, and errno can be inspected to find the cause of the failure, if any.
.PP
All source strings must be complete numbers without trailing characters.
Sources like "123asb" are not cool, neither are "123 " or "". We want numbers,
nothing else.
.SH AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
