.TH wlock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
wlock \- a lock one can wait on. 
.SH SYNOPSIS
.B #include <meta_wlock.h>
.sp
.BI "wlock wlock_new(void);

.BI "void wlock_free(wlock p);

.BI "int wlock_lock(wlock p);

.BI "int wlock_unlock(wlock p);

.BI "int wlock_signal(wlock p);

.BI "int wlock_wait(wlock p);

.BI "int wlock_broadcast(wlock p);

.SH DESCRIPTION
The wlock ADT implements a waitable/signalable lock as one
atomic type. It's a traditional combination of a mutex and
a condition variable.
