.TH wlock 3 2016-01-30 "" "The Meta C Library"
.SH NAME
wlock \- a lock one can wait on. 
.SH SYNOPSIS
.B #include <meta_wlock.h>
.sp
.Fo "wlock wlock_new"
.Fa "void"
.Fc
.Fo "void wlock_free"
.Fa "wlock p"
.Fc
.Fo "int wlock_lock"
.Fa "wlock p"
.Fc
.Fo "int wlock_unlock"
.Fa "wlock p"
.Fc
.Fo "int wlock_signal"
.Fa "wlock p"
.Fc
.Fo "int wlock_wait"
.Fa "wlock p"
.Fc
.Fo "int wlock_broadcast"
.Fa "wlock p"
.Fc
.SH DESCRIPTION
The wlock ADT implements a waitable/signalable lock as one
atomic type. It's a traditional combination of a mutex and
a condition variable.
