.TH wlock_new 3 2016-01-30 "" "The Meta C Library"
.TH wlock_free 3 2016-01-30 "" "The Meta C Library"
.SH NAME
.Nm wlock_new
.Nm wlock_free
.Nd create and destroy waitable locks.
.SH SYNOPSIS
.B #include <meta_wlock.h>
.sp
.BI "wlock wlock_new(void);

.BI "void wlock_fee(wlock lock);

.SH DESCRIPTION
.Nm wlock_new()
and
.Nm wlock_free()
creates and destroys waitable locks.
