.TH wlock_new 3
.TH wlock_free 3
.SH NAME
.Nm wlock_new
.Nm wlock_free
.Nd create and destroy waitable locks.
.SH SYNOPSIS
.Fd #include <meta_wlock.h>
.Fo "wlock wlock_new"
.Fa "void"
.Fc
.Fo "void wlock_fee"
.Fa "wlock lock"
.Fc
.SH DESCRIPTION
.Nm wlock_new()
and
.Nm wlock_free()
creates and destroys waitable locks.
.SH AUTHOR
.An bjorn.augestad@gmail.com
