.Dd Nov 25, 2005
.Os POSIX
.Dt HIGHLANDER
.Th response_set_etag 3
.Sh NAME
.Nm response_set_etag()
.Nd response_set_etag
.Sh SYNOPSIS
.Fd #include <highlander.h>
.Fo "int response_set_etag"
.Fa "http_response response"
.Fa "const char* value"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Nm
returns 1 on success and 0 if we ran out of memory.
.Sh EXAMPLE
.Bd -literal
.Ed
.Sh SEE ALSO
.Sh AUTHOR
.An B. Augestad, bjorn@augestad.online
