.Dd Nov 25, 2005
.Os POSIX
.Dt HIGHLANDER
.Th response_set_proxy_authenticate 3
.Sh NAME
.Nm response_set_proxy_authenticate()
.Nd Set the HTTP Proxy-Authenticate: field
.Sh SYNOPSIS
.Fd #include <highlander.h>
.Fo "int response_set_proxy_authenticate"
.Fa "http_response response"
.Fa "const char *value"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh EXAMPLE
.Bd -literal
.Ed
.Sh SEE ALSO
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
