#!/bin/bash
# We test the hello world program by 
# a) starting the server
# b) Issuing a get request, e.g. using wget
# c) interpret the result
# d) stop the server
# e) report the result

# We test under meson and it always builds to build-dir, and
# passes the name of the executable to us as arg1.
EXE=$1

if test ! -f "$EXE"; then
    echo "Meh, could not see executable"
    exit 1
fi

FACIT="<html><head><title>Hello, world</title></head><body>Hello, world</body></html>"

# Kill other instances, if any
killall -qw helloworld > /dev/null 2>&1

# Is someone else listening?
sudo netstat -tlnp

$EXE -t > logfile 2>&1 &
sleep 0.5

curl -s -o /tmp/x localhost:2000
GOT=$?
killall -qw helloworld > /dev/null 2>&1

if test $GOT -ne 0; then
    echo "meh 1"
    exit 1
fi

REPLY=$(cat /tmp/x)
if test "$REPLY" != "$FACIT" ; then
    echo "Expected: $FACIT"
    echo "Received: $REPLY"
    exit 1
fi

echo "Skipping test of TLS due to cert location issues"
exit 0

# Rinse and repeat for https
killall -qw helloworld > /dev/null 2>&1
sleep 1

# Is someone else listening?
sudo netstat -tlnp

$EXE > logfile2 2>&1 &
sleep 2

# wget -O /tmp/x --no-check-certificate --secure-protocol=auto https://localhost:2000 > /dev/null 2>&1
curl -s -o /tmp/x https://localhost:2000

GOT=$?
killall -qw helloworld > /dev/null 2>&1

if test $GOT -ne 0; then
    echo "meh 2"
    exit 1
fi

REPLY=$(cat /tmp/x)
if test "$REPLY" != "$FACIT" ; then
    echo "Expected: $FACIT"
    echo "Received: $REPLY"
    exit 1
fi

echo 0

