.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th array_nelem 3
.Sh NAME
.Nm array_nelem
.Nd Returns the number of elements in a dynamic array
.Sh SYNOPSIS
.Fd #include <meta_array.h>
.Fo "int array_nelem"
.Fa "array p"
.Fc
.Sh DESCRIPTION
Returns the number of elements in a dynamic array
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
