.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th bitset_is_set 3
.Sh NAME
.Nm bitset_is_set
.Nd Is a bit set
.Sh SYNOPSIS
.Fd #include <meta_bitset.h>
.Fo "int bitset_is_set"
.Fa "bitset b"
.Fa "size_t i"
.Fc
.Sh DESCRIPTION
Returns 1 if the bit specified is set, 0 if not.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
