.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th cache_remove 3
.Sh NAME
.Nm cache_remove
.Nd Remove an item from a cache
.Sh SYNOPSIS
.Fd #include <meta_cache.h>
.Fo "int cache_remove"
.Fa "cache c"
.Fa "size_t id"
.Fc
.Sh DESCRIPTION
Remove an item from a cache
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
