.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th configfile_read 3
.Sh NAME
.Nm configfile_read
.Nd Read and parse a configuration file
.Sh SYNOPSIS
.Fd #include <meta_configfile.h>
.Fo "configfile configfile_read"
.Fa "const char *path"
.Fc
.Sh DESCRIPTION
Read and parse a configuration file.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

