.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th configfile_get_int 3
.Sh NAME
.Nm configfile_get_int
.Nd Retrieve an int value from the configfile.
.Sh SYNOPSIS
.Fd #include <meta_configfile.h>
.Fo "int configfile_get_int"
.Fa "configfile cf"
.Fa "const char *name"
.Fa "int *value"
.Fc
.Sh DESCRIPTION
Retrieve an int value from the configfile.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com

