.Dd Nov 25, 2005
.Os POSIX
.Dt CONNECTION
.Th connection_readbuf_size 3
.Sh NAME
.Nm connection_readbuf_size()
.Nd Returns size of read buffer
.Sh SYNOPSIS
.Fd #include <connection.h>
.Fo "size_t connection_readbuf_size"
.Fa "connection conn"
.Fc
.Sh DESCRIPTION
.Nm
returns the size of the readbuffer.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
