.Dd Nov 25, 2005
.Os POSIX
.Dt CONNECTION
.Th connection_new 3
.Sh NAME
.Nm connection_new
.Nd Create a new connection
.Sh SYNOPSIS
.Fd #include <connection.h>
.Fo "connection connection_new"
.Fa "int timeout_reads"
.Fa "int timeout_writes"
.Fa "int retries_reads"
.Fa "int retries_writes"
.Fa "void* arg2"
.Fc
.Sh DESCRIPTION
.Nm
creates an instance of the connection ADT. 
.Pp
The tcp_server creates a given number of connections when the 
tcp_server is initialized. These connections are later supplied
to the caller of the tcp_server whenever a new connection from
a client is accepted by the server.
.Pp
The arg2 parameter is an optional pointer value which will be 
returned to the callback function when a new connection is made.
One possible and quite common use of arg2 is to store a handle
to the service that the tcp_server is used for. Imagine that
you have created more than one http_server within the same process.
Each http_server will then have its own instance, possibly 
represented as a malloced() pointer. At the same time, both
http_servers can share the callback function. arg2 can be used
to identify which http_server the connection was made to.
.Pp
Users of tcp_server never has to call this function.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
