.Dd Nov 25, 2005
.Os POSIX
.Dt CSTRING
.Th cstring_upper 3
.Sh NAME
.Nm cstring_upper()
.Nd Convert lower case to upper case letters.
.Sh SYNOPSIS
.Fd #include <cstring.h>
.Fo "void cstring_upper"
.Fa "cstring s"
.Fc
.Sh DESCRIPTION
.Nm
converts lower case letters to upper case letters.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
