.Dd Nov 25, 2005
.Os POSIX
.Dt CSTRING
.Th cstring_charcat 3
.Sh NAME
.Nm cstring_charcat()
.Nd Append a character to a cstring
.Sh SYNOPSIS
.Fd #include <cstring.h>
.Fo "int cstring_charcat"
.Fa "cstring dest"
.Fa "int c"
.Fc
.Sh DESCRIPTION
.Nm
appends the character
.Fa c
to the string
.Fa dest
 .
.Sh RETURN VALUE
.Nm
returns 1 if the character was successfully appended to the
string
.Fa dest
, or 0 if 
.Nm
was unable to allocate memory.
.Sh SEE ALSO
.Xr cstring_concat 3 ,
.Xr cstring_concat2 3 ,
.Xr cstring_concat3 3
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
