.Dd Nov 25, 2005
.Os POSIX
.Dt CSTRING
.Th cstring_reverse 3
.Sh NAME
.Nm cstring_reverse()
.Nd Reverse the contents of a cstring.
.Sh SYNOPSIS
.Fd #include <cstring.h>
.Fo "void cstring_reverse"
.Fa "cstring s"
.Fc
.Sh DESCRIPTION
.Nm
reverses the contents of 
.Fa s.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
