.Dd Nov 25, 2005
.Os POSIX
.Dt CSTRING
.Th cstring_strip 3
.Sh NAME
.Nm cstring_strip()
.Nd Strip leading and trailing white space from a string.
.Sh SYNOPSIS
.Fd #include <cstring.h>
.Fo "void cstring_strip"
.Fa "cstring s"
.Fc
.Sh DESCRIPTION
.Nm
strips leading and trailing white space from a string.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
