.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th fifo_nelem 3
.Sh NAME
.Nm fifo_nelem
.Nd Returns the number of elements in the fifo.
.Sh SYNOPSIS
.Fd #include <meta_fifo.h>
.Fo "size_t fifo_nelem"
.Fa "fifo p"
.Fc
.Sh DESCRIPTION
Returns the number of elements in the fifo.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
