.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th fifo_peek 3
.Sh NAME
.Nm fifo_peek
.Nd A thread safe FIFO ADT.
.Sh SYNOPSIS
.Fd #include <meta_fifo.h>
.Fo "void fifo_peek"
.Fa "fifo p"
.Fa "size_t i"
.Fc
.Sh DESCRIPTION
Retrieves any item from the fifo without removing it from the fifo.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
