.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th filecache 3
.Sh NAME
.Nm filecache
.Dd Nov 29, 2014
.Os POSIX
.Dt FILECACHE
.Th filecache_new 3
.Sh NAME
.Nm filecache_new
.Nd Short desc here
.Sh SYNOPSIS
.Fo "filecache filecache_new"
.Fa "size_t nelem"
.Fa "size_t bytes"
.Fc
.Sh DESCRIPTION
.Nm filecache_new()
long desc goes here.
.Sh AUTHOR
.An Bjorn Augestad bjorn.augestad@gmail.com
.Nd General purpose filecache ADT
.Sh SYNOPSIS
.Fd #include <filecache.h>
.Sh DESCRIPTION
The filecache ADT is a 
This ADT reads files from disk and caches them in memory.
The files can later be accessed directly in user space without
any kernel calls. This is A Good Thing as it avoids
slow context switches.
.Pp
You can specify both the number of files you want to be
able to cache, as well as the total number of bytes
you want the cache to use.
.Pp
The file name is used to identify each file, and the file cache
ignores symbolic links.
.Pp
The file cache is fully thread safe, and the initial design
was done to support the Highlander when running as an
image server.
.Pp
Algorithm: The file cache implements a traditional LRU
algorithm and will remove the LRU entry when the cache is
full and a new request is made. See cache.h for more details
as filecache just builds on cache.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
