.Dd Nov 25, 2005
.Th list_last 3
.Sh NAME
.Nm list_last() 
.Nd Is the current node the last node?
.Sh SYNOPSIS
.Fd #include <meta_list.h>
.Fo "int list_last"
.Fa "list_iterator li"
.Fc
.Sh DESCRIPTION
.Nm
returns true if the next call to list_next() will return NULL.
Returns false, 0, if there are more items in the list.
.Sh EXAMPLE
.Bd -literal
/* How and when to use list_last() */
printf("Names of all objects: ");
for(i = list_first(my_list); !list_end(i); i = list_next(i)) {
   my_object = list_get(i);
   printf("%s", get_name(my_object));
   if(list_last(i))
       printf(".\n");
   else
       printf(", ");
}
.Ed
.Sh AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
