.Dd Nov 25, 2005
.Th list_first 3
.Sh NAME
.Nm list_first() 
.Nd Return an iterator to the first node in a list.
.Sh SYNOPSIS
.Fd #include <meta_list.h>
.Fo "list_iterator list_first"
.Fa "list lst"
.Fc
.Sh DESCRIPTION
.Nm
returns an iterator to the first item. Use list_end() to test if we reached the end 
of the list, i.e. the list was empty.
.Sh AUTHOR
B. Augestad, bjorn.augestad@gmail.com.
