.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th pool_add 3
.Sh NAME
.Nm pool_add
.Nd Object management ADT
.Sh SYNOPSIS
.Fd #include <meta_pool.h>
.Fo "void* pool_add"
.Fa "pool p"
.Fa "void *resource"
.Fc
.Sh DESCRIPTION
Adds a new resource to the resource pool. 
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
