.Dd Nov 25, 2005
.Os POSIX
.Dt META_PROCESS
.Th process_get_exitcode 3
.Sh NAME
.Nm process_get_exitcode()
.Nd Get exit code from a thread
.Sh SYNOPSIS
.Fd #include <meta_process.h>
.Fo "int process_get_exitcode"
.Fa "process p"
.Fa "void* object"
.Fc
.Sh DESCRIPTION
.Nm
Returns the exit code from the objects run() function. 
It will return -1 for any invalid pointers to object.
.Fa object
is used to locate a previously added object.
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
