.Dd Nov 25, 2005
.Os POSIX
.Dt HIGHLANDER
.Th response_set_expires 3
.Sh NAME
.Nm response_set_expires()
.Nd Set the HTTP Expires field
.Sh SYNOPSIS
.Fd #include <highlander.h>
.Fo "int response_set_expires"
.Fa "http_response response"
.Fa "time_t value"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh EXAMPLE
.Bd -literal
.Ed
.Sh SEE ALSO
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
