.Dd Nov 29, 2014
.Os POSIX
.Dt SOCK
.Th sock_write 3
.Sh NAME
.Nm sock_write
.Nd Write data to socket.
.Sh SYNOPSIS
.Fd #include <meta_sock.h>
.Fo "int sock_write"
.Fa "meta_socket p"
.Fa "const char *s"
.Fa "size_t count"
.Fa "int timeout"
.Fa "int retries"
.Fc
.Sh DESCRIPTION
.Nm
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
