.Dd Nov 29, 2014
.Os POSIX
.Dt SOCK
.Th sock_accept 3
.Sh NAME
.Nm sock_accept
.Nd Y
.Sh SYNOPSIS
.Fd #include <meta_sock.h>
.Fo "meta_socket sock_accept"
.Fa "meta_socket p"
.Fa "struct sockaddr *addr"
.Fa "socklen_t *addrsize"
.Fc
.Sh DESCRIPTION
.Nm
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
