.Dd Nov 25, 2005
.Os POSIX
.Dt META
.Th tcp_server_set_port 3
.Sh NAME
.Nm tcp_server_set_port()
.Nd Set the port number to listen on.
.Sh SYNOPSIS
.Fd #include <tcp_server.h>
.Fo "void tcp_server_set_port"
.Fa "tcp_server srv"
.Fa "int port"
.Fc
.Sh DESCRIPTION
Sets the port number that the tcp_server will listen to.
The tcp_server will by default listen to port 2000. Listening to
ports below 1024 requires that root starts the process.
.Sh SEE ALSO
.Xr process tcp_server_get_root_resources 3
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
