#!/bin/bash

gcc -fsanitize=undefined -O0 -ggdb -o json -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=c99 json.c -lmeta
if test $? -ne 0; then
    exit 1
fi

gcc -DNDEBUG -O3 -march=native -mtune=native -o fastjson -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=c99 json.c -lmeta
if test $? -ne 0; then
    exit 1
fi

