#!/bin/bash

gcc -D_POSIX_C_SOURCE=200112L -fsanitize=undefined -O0 -ggdb -o json -I../meta/src  -DJSON_CHECK -Werror -Wshadow -Wall -Wextra -pedantic -std=gnu11 json.c -lmeta
if test $? -ne 0; then
    exit 1
fi

gcc -D_POSIX_C_SOURCE=200112L -DNDEBUG -O3 -march=native -mtune=native -o fastjson -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=gnu11 json.c -lmeta
if test $? -ne 0; then
    exit 1
fi

exitcode=0
# Test all the y_files, which all must succeed with exit code 0
FILES=$(cat y_files)
for i in $FILES; do
    $VG ./json $i
    if test $? -ne 0; then
        echo "fail: $i"
        exitcode=1
    fi
done

# Test all the n_files, which all must succeed with exit code <> 0
FILES=$(cat n_files)
for i in $FILES; do
    $VG ./json $i >& /dev/null 
    if test $? -eq 0; then
        echo "should've failed: $i"
        exitcode=1
    fi
done


# Test all the i_files, which are open to interpretation
# Let's just see how they fare
FILES=$(cat i_files)
for i in $FILES; do
    $VG ./json $i >& /dev/null 
    #if test $? -eq 0; then
        #echo "interpret succ: $i"
    #else
        #echo "interpret fail: $i"
    #fi
done


exit $exitcode
